services:
  mysql:
    image: mysql:8.4
    container_name: matkinhDb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: matkinh
      MYSQL_USER: matkinh
      MYSQL_PASSWORD: matkinh123

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema_mysql.sql:/docker-entrypoint-initdb.d/schema_mysql.sql:ro

volumes:
  mysql_data: